"""empty message

Revision ID: 8aed9a6ba4e5
Revises: 39481728eaad
Create Date: 2024-01-23 13:05:13.052164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aed9a6ba4e5'
down_revision: Union[str, None] = '39481728eaad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_pregnant_replaced', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_column('user', 'is_pregnant_replaced')
    # ### end Alembic commands ###
