"""empty message

Revision ID: 9365a5963c95
Revises: 0f8a2ac3c358
Create Date: 2024-02-01 14:38:50.986147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9365a5963c95'
down_revision: Union[str, None] = '0f8a2ac3c358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('fk_dep', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_dep'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_id'), 'risk', ['id'], unique=False)
    op.create_table('control_group',
    sa.Column('fk_risk_id', sa.Integer(), nullable=False),
    sa.Column('fk_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['fk_risk_id'], ['risk.id'], ),
    sa.PrimaryKeyConstraint('fk_risk_id', 'fk_post_id')
    )
    op.create_table('executor_group',
    sa.Column('fk_risk_id', sa.Integer(), nullable=False),
    sa.Column('fk_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['fk_risk_id'], ['risk.id'], ),
    sa.PrimaryKeyConstraint('fk_risk_id', 'fk_post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executor_group')
    op.drop_table('control_group')
    op.drop_index(op.f('ix_risk_id'), table_name='risk')
    op.drop_table('risk')
    # ### end Alembic commands ###
